services:
  _defaults:
    autowire: true
    autoconfigure: false

  AASHRO\AtMedicare\EventListener\PackageActivationListener:
    public: false
    tags:
      - name: event.listener
        identifier: 'at-medicare-package-activation'
        event: TYPO3\CMS\Core\Package\Event\PackageInitializationEvent

